# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true
